apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: go-simple-webserver
  labels:
    app: go-simple-webserver
spec:
  replicas: 10
  strategy:
    canary:
      steps:
        - setWeight: 50
        - pause: { duration: 60s }
        - setWeight: 100
  selector:
    matchLabels:
      app: go-simple-webserver
  template:
    metadata:
      labels:
        app: go-simple-webserver
    spec:
      containers:
        - name: webserver
          image: ghcr.io/adrianstefan3//ci_cd_lab@sha256:bccf7e64fbe28c360687f9c8e3793a9d2345c5b19476681afbc1942b5f394c9c
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
